spring:
  kafka:
    bootstrap-servers: [localhost:29092, localhost:39092, localhost:49092]
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer